In [1]:
import numpy as np
import torch

In [3]:
# MxN matrix (M = rows, N = columns)

# MxN * NxK = MxK Note: first matrix columns shape must be equal second matrix rows shape.

In [8]:
# create some random matrices

A = np.random.randn(3, 4)
B = np.random.randn(4, 5)
C = np.random.randn(3, 7)

# print(np.round(A@B, 2)) #@ -> matrix multiplication
# print(np.round(A@C, 2)) # Error.
# print(np.round(B@C, 2)) # Error.
print(np.round(C.T@A, 2))

[[ 0.42  1.   -0.31  0.47]
 [-0.46 -2.25 -1.26 -0.58]
 [-1.08  0.46  1.46  0.18]
 [-1.29  2.14  0.57  1.47]
 [ 1.23  1.34 -3.41  1.39]
 [ 0.22  1.24  1.54  0.04]
 [ 0.12  4.27  0.72  1.98]]


In [14]:
# using pytorch
# create some random matrices

A = torch.randn(3, 4)
B = torch.randn(4, 5)
C = np.random.randn(4, 7)
C1 = torch.tensor(C, dtype=torch.float)


# print(np.round(A@B, 2))
# print(np.round(A@C, 2))
# print(np.round(A@C1, 2))
# print(np.round(B@C, 2))

tensor([[ 0.1900,  1.1000,  0.7900, -0.3400,  0.4600,  0.2100, -3.2800],
        [-0.1900, -0.0800, -0.9200, -0.5200, -0.1200, -0.3400, -0.2500],
        [ 0.9200,  0.3100,  2.2700,  1.7600,  1.3900, -0.3600, -0.6500]])
