In [4]:
import numpy as np
import torch

In [10]:
# create a vector
nv = np.array([[1, 2, 3, 4]])
print(nv)

# transpose it
print("Transpose: ")
print(nv.T)

# transpose the transpose!
nvT = nv.T
print("Transpose the transpose: ")
print(nvT.T)

[[1 2 3 4]]
Transpose: 
[[1]
 [2]
 [3]
 [4]]
Transpose the transpose: 
[[1 2 3 4]]


In [11]:
# create a matrix
nM = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(nM)

# transpose it
print("Transpose: ")
print(nM.T)

# transpose the transpose!
nMT = nM.T
print("Transpose the transpose: ")
print(nMT.T)

[[1 2 3 4]
 [5 6 7 8]]
Transpose: 
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
Transpose the transpose: 
[[1 2 3 4]
 [5 6 7 8]]


In [13]:
# Same operations with pytorch.

# create a vector
tv = torch.tensor([[1, 2, 3, 4]])
print(tv)

# transpose it
print("Transpose: ")
print(tv.T)

# transpose the transpose!
tvT = tv.T
print("Transpose the transpose: ")
print(tvT.T)

tensor([[1, 2, 3, 4]])
Transpose: 
tensor([[1],
        [2],
        [3],
        [4]])
Transpose the transpose: 
tensor([[1, 2, 3, 4]])


In [14]:
# create a matrix
tM = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
print(tM)

# transpose it
print("Transpose: ")
print(tM.T)

# transpose the transpose!
tMT = tM.T
print("Transpose the transpose: ")
print(tMT.T)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
Transpose: 
tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])
Transpose the transpose: 
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [15]:
print(f"Variable nv is of type {type(nv)}")
print(f"Variable nM is of type {type(nM)}")
print(f"Variable tv is of type {type(tv)}")
print(f"Variable tM is of type {type(tM)}")

Variable nv is of type <class 'numpy.ndarray'>
Variable nM is of type <class 'numpy.ndarray'>
Variable tv is of type <class 'torch.Tensor'>
Variable tM is of type <class 'torch.Tensor'>
